### ISSUE TITLE
Dashboard should inform you if WebSocket connection has dropped

### ISSUE THREAD

**Issue by joshproehl** [ValleyCamp/WeatherMoss#1]
Currently the user has no way to know that they're not seeing updated data except to notice that the lines aren't updating. If a connection drops an overlay should appear informing the user to refresh the page. 

Or perhaps the page should be forcibly refreshed?

**Comment by Tenaciousmoss** [comment]
Is it possible to add a timer that shows the minutes since the last 'new
data' arrived?
